config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'

  get 'profile' => 'user#profile'
  get 'settings' => 'users#edit'


  get '/dashboard', to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tours do
    resources :reservations, only: [:new, :create] do
      resources :reviews, only: [:new, :create]
    end
    resources :favorites, only: [:new, :create]
  end

  resources :reservations, only: [:index, :show, :destroy, :update]
  resources :favorites, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :tour
  has_one :review, dependent: :destroy

  # Validations
  validates :date, presence: true
  validates :amount_of_people, presence: true, length: { minimum: 1 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reservation

  # Validations
  validates :reservation, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tours, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  # has_many :chatrooms, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  protected

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :avatar)}

   devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :name, :email, :password, :current_password, :avatar)}
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # def index
  #   @tour = Tour.find(params[:id])
  #   @favorites = Favorite.all
  # end

  def create
    @favorite = Favorite.new
    @favorite.user = current_user
    @tour = Tour.find(params[:tour_id])
    @favorite.tour = @tour
    authorize(@favorite)
    @favorite.save
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js {}
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    authorize(@favorite)
    @tour = @favorite.tour
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js {}
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @tours = Tour.all
    if params[:query].present?
      sql_query = " \
      tours.category @@ :query \
      tours.city @@ :query \
      tours.description @@ :query \
      "
      @tours = Tour.where(sql_query, query: "%#{params[:query]}%")
    else
      @tours = Tour.all
    end
  end

  def dashboard
    # @reservations = policy_scope(Reservation).where(user: current_user).order(created_at: :desc)
    @requests = Reservation.joins(:tour).where(tour: { user: current_user }).reverse_order
    # @user = current_user
    # @tour.user = @user
    @favorites = Favorite.all
    # @favorites = current_user.favorites
    @reservation = Reservation.new
    @reservations = Reservation.all.reverse_order
    @tours = Tour.all.reverse_order
    # @chatroom = Chatroom.find_or_create_by(tour: @tour, user: current_user)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = policy_scope(Reservation).where(user: current_user).order(created_at: :desc)
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
    authorize(@reservation)
  end

  def create
    @user = current_user
    @tour = Tour.find(params[:tour_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.user = @user
    @reservation.tour = @tour
    if @reservation.date != nil
      authorize(@reservation)
      if @reservation.save
        # redirect_to reservation_path(@reservation), notice: "Reservation was saved succsessfully!"
        # redirect_to tour_path(@tour), notice: "Reservation was saved succsessfully!"
      else
        redirect_to tour_path(@tour), notice: "Could not create Reservation!"
      end
    else
      authorize(@reservation)
      redirect_to tour_path(@tour), notice: "Enter a Date for the Reservation!"
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    authorize(@reservation)
    @reservation.destroy
    redirect_to dashboard_path, notice: "Reservation was cancelled succsesfully!"
  end

  def update
    @reservation = Reservation.find(params[:id])
    authorize(@reservation)

    if params[:approve] == "true"
      @reservation.approved = true
      @reservation.declined = false
    else
      @reservation.declined = true
      @reservation.approved = false
    end
    @reservation.save
  end

  private

  def reservation_params
    params.require(:reservation).permit(:user_id, :tour_id, :date, :amount_of_people, :total_price, :approved)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @tour = Tour.find(params[:tour_id])
    @reservation = Reservation.find(params[:reservation_id])
    authorize(@review)
  end

  def create
    @review = Review.new(review_params)
    @review.reservation = Reservation.find(params[:reservation_id])
    authorize(@review)
    if @review.save
      redirect_to tours_path
    else
      flash[:alert] = "Something went wrong. Please try again later!"
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:tour_rating, :review_description)
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_tour, only: %i[show edit update destroy]
  def index
    @tours = policy_scope(Tour).order(created_at: :desc)
    @tours = Tour.all
    if params[:query].present?
      sql_query = "category ILIKE :query OR city ILIKE :query"

      # @tours = Tour.where("category ILIKE ?", "%#{params[:query]}%")
      @tours = Tour.where(sql_query, query: "%#{params[:query]}%")
    else
      @tours = Tour.all
    end
    @favorite = Favorite.new
  end

  def show
    authorize(@tour)
    @tour = Tour.find(params[:id])
    @reservations = Reservation.all
    @reservations = Reservation.new
    @favorite = Favorite.new
  end

  def new
    @tour = Tour.new
    authorize(@tour)
  end

  def create
    if current_user.role == "Admin" || current_user.role == "Tour Guide"
      @tour = Tour.create(tour_params)
      @user = current_user
      @tour.user = @user
      authorize(@tour)
      if @tour.save
        redirect_to tour_path(@tour)
      else
        render :show
      end
    else
      render :index
    end

  end

  def edit
    authorize(@tour)
  end

  def update
    authorize(@tour)
    @tour.update(tour_params)
    if @tour.save
      redirect_to tours_path
    else
      render :edit
    end
  end

  def destroy
    @tour.destroy
    redirect_to tours_path
  end

  private

  def tour_params
    params.require(:tour).permit(:name, :city, :description, :duration, :price, :category, photos: [])
  end

  def set_tour
    @tour = Tour.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <footer class="">
    <div class="custom-container footer-responsive pb-md-4">
      <div class="footer-links footer-design">
        <%= image_tag "logo2.png", alt: "This is the logo of tours of the day", class: "footer-logo" %>
        <%= form_tag tours_path, method: :get do %>
            <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search for a City?" %>
        <% end %>
      </div>
      <div class="footer-links">
        <h6 class="subtitle">Tours</h6>
        <%= link_to "All Tours", tours_path %>
        <%= link_to "Features", root_path %>
        <%= link_to "Tutorials", root_path %>
        <%= link_to "Process", root_path %>
        <%= link_to "Releases", root_path %>
      </div>
      <div class="footer-links">
        <h6 class="subtitle">Company</h6>
        <%= link_to "About Us", root_path %>
        <%= link_to "Blog", root_path %>
        <%= link_to "Careers", root_path %>
        <%= link_to "Contact", root_path %>
        <%= link_to "Press", root_path %>
      </div>
      <div class="footer-links">
        <h6 class="subtitle">Support</h6>
        <%= link_to "Become a Guide", root_path %>
        <%= link_to "Cookies Policy", root_path %>
        <%= link_to "Privacy Policy", root_path %>
        <%= link_to "Terms of Use", root_path %>
        <%= link_to "Sitemap", root_path %>
      </div>
    </div>
    <hr class="footer-hr ">
    <div class="custom-container copyright-social-media">
      <p class="text-center">&copy;2021 Tour of the Day. All right reserved</p>
      <div class="footer-social">
        <i class="fab fa-facebook-f ml-4">
        </i>
        <i class="fab fa-instagram ml-2">
        </i>
        <i class="fab fa-twitter ml-2 ">
        </i>
        <i class="fab fa-pinterest-p ml-2">
        </i>
      </div>
    </div>
  </footer>
  <div id="back-top">
    <a href="#">
      <i class="fas fa-angle-up">
      </i>
    </a>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-custom-layout">
  <div class="custom-container">
    <div class="navbar navbar-expand-sm navbar-light navbar-tours">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo2.png", class: "logo-style" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="">
              <%= link_to "All Tours", tours_path, class: "nav-link" %>
            </li>
            <% if user_signed_in? %>
              <% if current_user.role == "Admin" || current_user.role == "Tour Guide" %>
                <li class="">
                  <%= link_to "Create a Tour", new_tour_path, class: "nav-link" %>
                </li>
              <% end %>
              <li class="nav-item">
                <%= link_to "Messages", "#", class: "nav-link mr-3" %>
              </li>
              <li class="nav-item dropdown">
              <% if current_user.avatar.attached? %>
                <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
                <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="d-flex">
              <%= link_to "Login", new_user_session_path, class: "login-button" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="sub-nav d-flex justify-content-center">
  <div class=" w-100">
    <ul class="d-flex sub-nav-tabs w-100 py-2">
      <li><%= link_to "City Tour", tours_path(:query => "City Tour"), class: "sub-nav-tab-link" %></li>
      <li><%= link_to "Boat Tour", tours_path(:query => "Boat Tour"), class: "sub-nav-tab-link" %></li>
      <li><%= link_to "Private Tours", tours_path(:query => "Private Tours"), class: "sub-nav-tab-link" %></li>
      <li><%= link_to "Bike Tour", tours_path(:query => "Bike Tour"), class: "sub-nav-tab-link" %></li>
      <li><%= link_to "Museum Guide", tours_path(:query => "Museum Guide"), class: "sub-nav-tab-link" %></li>
      <li><%= link_to "Night Tour", tours_path(:query => "Night Tour"), class: "sub-nav-tab-link" %></li>
      <li><%= link_to "Keukenhof", tours_path(:query => "Keukenhof"), class: "sub-nav-tab-link" %></li>
      <li><%= link_to "Food Tour", tours_path(:query => "Food Tour"), class: "sub-nav-tab-link" %></li>
      <li><%= link_to "See all Categories", tours_path, class: "sub-nav-tab-link no-border" %></li>
    </ul>
  </div>
</div>