config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'

  get 'profile' => 'user#profile'
  get 'settings' => 'users#edit'


  get '/dashboard', to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tours do
    resources :reservations, only: [:new, :create] do
      resources :reviews, only: [:new, :create]
    end
    resources :favorites, only: [:new, :create]
  end

  resources :reservations, only: [:index, :show, :destroy, :update]
  resources :favorites, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :tour
  has_one :review, dependent: :destroy

  # Validations
  validates :date, presence: true
  validates :amount_of_people, presence: true, length: { minimum: 1 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reservation

  # Validations
  validates :reservation, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tours, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  # has_many :chatrooms, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  protected

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :avatar)}

   devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :name, :email, :password, :current_password, :avatar)}
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # def index
  #   @tour = Tour.find(params[:id])
  #   @favorites = Favorite.all
  # end

  def create
    @favorite = Favorite.new
    @favorite.user = current_user
    @tour = Tour.find(params[:tour_id])
    @favorite.tour = @tour
    authorize(@favorite)
    @favorite.save
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js {}
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    authorize(@favorite)
    @tour = @favorite.tour
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js {}
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @tours = Tour.all
    if params[:query].present?
      sql_query = " \
      tours.category @@ :query \
      tours.city @@ :query \
      tours.description @@ :query \
      "
      @tours = Tour.where(sql_query, query: "%#{params[:query]}%")
    else
      @tours = Tour.all
    end
  end

  def dashboard
    # @reservations = policy_scope(Reservation).where(user: current_user).order(created_at: :desc)
    @requests = Reservation.joins(:tour).where(tour: { user: current_user }).reverse_order
    # @user = current_user
    # @tour.user = @user
    @favorites = Favorite.all
    # @favorites = current_user.favorites
    @reservation = Reservation.new
    @reservations = Reservation.all.reverse_order
    @tours = Tour.all.reverse_order
    # @chatroom = Chatroom.find_or_create_by(tour: @tour, user: current_user)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = policy_scope(Reservation).where(user: current_user).order(created_at: :desc)
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
    authorize(@reservation)
  end

  def create
    @user = current_user
    @tour = Tour.find(params[:tour_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.user = @user
    @reservation.tour = @tour
    if @reservation.date != nil
      authorize(@reservation)
      if @reservation.save
        # redirect_to reservation_path(@reservation), notice: "Reservation was saved succsessfully!"
        # redirect_to tour_path(@tour), notice: "Reservation was saved succsessfully!"
      else
        redirect_to tour_path(@tour), notice: "Could not create Reservation!"
      end
    else
      authorize(@reservation)
      redirect_to tour_path(@tour), notice: "Enter a Date for the Reservation!"
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    authorize(@reservation)
    @reservation.destroy
    redirect_to dashboard_path, notice: "Reservation was cancelled succsesfully!"
  end

  def update
    @reservation = Reservation.find(params[:id])
    authorize(@reservation)

    if params[:approve] == "true"
      @reservation.approved = true
      @reservation.declined = false
    else
      @reservation.declined = true
      @reservation.approved = false
    end
    @reservation.save
  end

  private

  def reservation_params
    params.require(:reservation).permit(:user_id, :tour_id, :date, :amount_of_people, :total_price, :approved)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @tour = Tour.find(params[:tour_id])
    @reservation = Reservation.find(params[:reservation_id])
    authorize(@review)
  end

  def create
    @review = Review.new(review_params)
    @review.reservation = Reservation.find(params[:reservation_id])
    authorize(@review)
    if @review.save
      redirect_to tours_path
    else
      flash[:alert] = "Something went wrong. Please try again later!"
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:tour_rating, :review_description)
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_tour, only: %i[show edit update destroy]
  def index
    @tours = policy_scope(Tour).order(created_at: :desc)
    @tours = Tour.all
    if params[:query].present?
      sql_query = "category ILIKE :query OR city ILIKE :query"

      # @tours = Tour.where("category ILIKE ?", "%#{params[:query]}%")
      @tours = Tour.where(sql_query, query: "%#{params[:query]}%")
    else
      @tours = Tour.all
    end
    @favorite = Favorite.new
  end

  def show
    authorize(@tour)
    @tour = Tour.find(params[:id])
    @reservations = Reservation.all
    @reservations = Reservation.new
    @favorite = Favorite.new
  end

  def new
    @tour = Tour.new
    authorize(@tour)
  end

  def create
    if current_user.role == "Admin" || current_user.role == "Tour Guide"
      @tour = Tour.create(tour_params)
      @user = current_user
      @tour.user = @user
      authorize(@tour)
      if @tour.save
        redirect_to tour_path(@tour)
      else
        render :show
      end
    else
      render :index
    end

  end

  def edit
    authorize(@tour)
  end

  def update
    authorize(@tour)
    @tour.update(tour_params)
    if @tour.save
      redirect_to tours_path
    else
      render :edit
    end
  end

  def destroy
    @tour.destroy
    redirect_to tours_path
  end

  private

  def tour_params
    params.require(:tour).permit(:name, :city, :description, :duration, :price, :category, photos: [])
  end

  def set_tour
    @tour = Tour.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/tours/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
  </ol>
  <div class="carousel-inner">
    <% @tour.photos.each_with_index do |photo, index|%>
      <div class="carousel-item <%= 'active' if index == 0 %>">
        <%= cl_image_tag photo.key, class: "carousel-size" %>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/tours/_favorite.html.erb
<%= render "favorites/favoriteJS" %>

app/views/tours/_reviewcards.html.erb
<h2>Reviews:</h2>
<div class="d-flex justify-content-between">
  <p>Average rating:</p>
  <p class="mr-3"> <strong class="bigger-font"> <%= @tour.average_rating %> </strong>/ 5</p>
</div>

<div>
  <div class="mb-3">
    <% @tour.reservations.each do |res| %>

      <div>
        <% if res.review != nil %>
          <div class="d-flex align-items-center mb-3">
            <% if  res.user.avatar.attached? %>
              <%= cl_image_tag res.user.avatar.key, class: 'avatar-large shadow' %>
            <% else %>
              <%= image_tag "https://images.unsplash.com/photo-1593099295589-ee5c1aa4164f?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2736&q=80", class: 'preview-avatar mb-2', width: '60px', height: '60px'%>
            <% end %>
            <div class=" px-3 w-100">
              <div class="d-flex justify-content-between">
                <p class="my-0"> <%= res.user.first_name %> </p>
                <div>
                  <% case res.review.tour_rating %>
                    <% when 0 %>
                      <i class="far fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i>
                    <% when 1 %>
                      <i class="fas fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i>
                    <% when 2 %>
                      <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i>
                    <% when 3 %>
                      <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i>
                    <% when 4 %>
                      <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="far fa-star"></i>
                    <% when 5 %>
                      <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star"></i> <i class="fas fa-star"></i>
                  <% end %>
                </div>
              </div>

              <p class="light-font my-0"> <%= res.review.created_at.strftime("%B %-d, %Y") %> </p>
              <p class="my-0 small-font"> <%= res.review.review_description%> </p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tours/_reviewstars.html.erb
<p> <i class="fas fa-star"></i> <%= tour.average_rating %> (<%= tour.reviews.count%>)</p>

app/views/tours/edit.html.erb
<div class="new-tour-bg py-5">
  <div class="container new-tour-form">
    <h1 class="pl-2">Edit Your Tour</h1>

    <div class="container">
      <%= simple_form_for @tour do |f| %>
        <div class="row">
          <div class="col-sm-10 col-md-12 col-lg-6 "> <%= f.input :name, label: "Tour Name" %></div>
          <div class="col-sm-10 col-md-12 col-lg-6 "> <%= f.input :city %></div>
          <div class="col-sm-10 col-md-12 col-lg-4 "> <%= f.input :price, label: "Price per person" %></div>
          <div class="col-sm-10 col-md-12 col-lg-4 "> <%= f.input :duration %></div>
          <div class="col-sm-10 col-md-12 col-lg-4 "> <%= f.input :category %></div>
          <div class="col-sm-10 col-md-12 col-lg-12 "> <%= f.input :description, label: "Tour description" %></div>
        </div>
        <label class="btn btn-dark">
          <i class="fas fa-images"></i> Add photos to your tour
          <span style="display:none;">
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          </span>
        </label>
        <div class="d-flex">
          <%= f.submit "Save Changes", class:'btn btn-danger' %>
          <%# if action_name == 'edit' %>
            <%#= link_to(@tour, method: :delete, data: { confirm: 'Are you sure?' }, class: "ml-2") do %>
            <!-- <i class="far fa-trash-alt"></i> -->
          <%# end %>
          <%# end %>
      </div>
    </div>
  <% end %>
</div>

app/views/tours/index.html.erb
<div class="">
  <div class="row cards-wrapper mt-4">
    <% @tours.each do |tour| %>
      <div class="col-sm-8 col-md-4 col-lg-3 card-trip">
        <% if tour.photos.attached? %>
        <%= cl_image_tag tour.photos[0].key %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <%= link_to tour_path(tour), class: "index-link pb-1" do %>
              <h2><%= tour.city %>: <%= tour.name %></h2>
            <% end %>
            <p class="mt-2 rating-index-style"> <i class="fas fa-star"></i> <%= tour.average_rating %> (<%= tour.reviews.count%> <%= tour.reviews.count > 1 ? "reviews" : "review" %>)</p>
            <p class="mt-2 tour-duration-index"><i class="far fa-clock"></i> <%= tour.duration %> <%= tour.duration == 1 ? "hour" : "hours" %></p>
            <!-- <p class="mt-2"><%= tour.description&.truncate(50, separator: " ") %></p> -->

          </div>
          <h2 class="card-trip-pricing">€<%= tour.price %> p/p</h2>
            <% if tour.user.avatar.attached? %>
              <%= cl_image_tag tour.user.avatar.key, class: 'card-trip-user avatar-bordered' %>
            <% else %>
              <%= image_tag "https://images.unsplash.com/photo-1485178575877-1a13bf489dfe?ixid=MXwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MXwyNDgzNjQ1fHxlbnwwfHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60", class: 'card-trip-user avatar-bordered' %>
            <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tours/new.html.erb
<div class="new-tour-bg py-5">
  <div class="container new-tour-form">
    <h1 class="pl-2">Create Your Tour</h1>

    <div class="container">
      <%= simple_form_for @tour do |f| %>
        <div class="row">
          <div class="col-sm-10 col-md-12 col-lg-6 "><%= f.input :name, label: "Tour Name", placeholder: ' Tour name... E.g. City Tour?' %> </div>
          <div class="col-sm-10 col-md-12 col-lg-6 "><%= f.input :city, placeholder: 'In what city is the tour? E.g. Amsterdam' %> </div>
          <div class="col-sm-10 col-md-12 col-lg-4 "><%= f.input :price, label: "Price per person", placeholder: 'What is the price of the tour? E.g. Price 150 p/p' %> </div>
          <div class="col-sm-10 col-md-12 col-lg-4 "><%= f.input :duration, label: "Tour Duration", placeholder: 'How long is the tour? E.g. 1 for one hour or 1,5 for one and half hour' %> </div>
          <div class="col-sm-10 col-md-12 col-lg-4 "><%= f.input :category, placeholder: 'E.g. private tour or group tour...' %> </div>
          <div class="col-sm-10 col-md-12 col-lg-12 "><%= f.input :description, as: :text, placeholder: 'Add here the description of you tour!' %> </div>
        </div>
      <label class="btn btn-dark">
        <i class="fas fa-images"></i> Add photos to your tour
        <span style="display:none;">
          <%= f.input :photos, as: :file, input_html: { multiple: true }, required: true %>
        </span>
      </label>

        <div class="d-flex">
          <%= f.submit "Create Tour", class:'btn btn-danger' %>
          <% if action_name == 'edit' %>
            <%= link_to(tour, method: :delete, data: { confirm: 'Are you sure?' }, class: "ml-2") do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tours/show.html.erb
<div class="custom-container">
  <div class="custom-container header-and-rating mt-3">
    <div class="d-flex justify-content-between">
    <h1><%= @tour.city %>: <%= @tour.name %></h1>
    <div class="d-flex mt-3">
      <% if user_signed_in? %>
        <% if @tour.user_id == current_user.id %>
          <%= link_to(edit_tour_path(@tour)) do %>
            <i class="far fa-edit mr-1"></i>
          <% end %>
          <%= link_to(@tour, method: :delete, data: { confirm: 'Are you sure?' }) do %>
          <i class="far fa-trash-alt">
          </i>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

    <div class="d-flex justify-content-between mt-3">
      <p> <i class="fas fa-star"></i> <%= @tour.average_rating %> (<%= @tour.reviews.count%> <%= @tour.reviews.count > 1 ? "reviews" : "review" %>)</p>
      <div> <%= render "favorite" %></div>
    </div>
  </div>

  <div class="custom-container d-flex rounded-lg">
    <div class="side-carousel-image mr-2">
      <%= cl_image_tag @tour.photos[1].key, class: "mb-2 show-image-size top-left-radius" %>
      <%= cl_image_tag @tour.photos[2].key, class: "show-image-size bottom-left-radius" %>
    </div>

    <div class="carousel">
      <%= render "carousel" %>
    </div>

      <div class="side-carousel-image ml-2">
      <%= cl_image_tag @tour.photos[3].key, class: "mb-2 show-image-size top-right-radius" %>
      <%= cl_image_tag @tour.photos[4].key, class: "show-image-size bottom-right-radius" %>
    </div>
  </div>

  <div class="custom-container my-4 description-booking-wrapper">
    <div class="tour-description-show">
      <p><%= @tour.description %></p>
      <h3><%#= @tour.city %></h3>
    </div>
    <div class="booking-form">
      <div class="booking-box">
        <h2>Book your Tour</h2>
        <%= simple_form_for ([@tour, @reservations]) do |f| %>
        <%= f.input :date, as: :date, html5: true %>
        <%= f.input :amount_of_people, input_html: { min: '1', step: 'any', value: "1" } %>
        <div class="details-show-price py-2 pr-1">
          <p class="text-center" id="priceCalculator" data-price="<%= @tour.price %>"> Total: € <%= number_with_precision(@tour.price, precision: 0) %> <span>per person</span></p>
        </div>
        <%= f.submit "Book Tour", class:"btn btn-danger w-100 button-design", data: { toggle: "modal", target: "#exampleModal" }  %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="custom-container w-100">
  <div class="custom-container mt-5">
    <div class="d-flex">
      <div class="review-card-box">
        <%= render "reviewcards" %>
      </div>
    </div>
  </div>
</div>



<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title text-center" id="exampleModalLabel">Thank you for your Booking</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex justify-content-center flex-column align-items-center">
        <p>You booked <%= @tour.city %>: <%= @tour.name %></p>
        <p>Waiting for <strong> <%= @tour.user.first_name %> <%= @tour.user.last_name %> </strong> to approve your booking</p>
        <%= link_to "Visit Your Dashboard", dashboard_path, class: "btn btn-danger my-3" %>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

      </div> -->
    </div>
  </div>
</div>