config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'

  get 'profile' => 'user#profile'
  get 'settings' => 'users#edit'


  get '/dashboard', to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tours do
    resources :reservations, only: [:new, :create] do
      resources :reviews, only: [:new, :create]
    end
    resources :favorites, only: [:new, :create]
  end

  resources :reservations, only: [:index, :show, :destroy, :update]
  resources :favorites, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :tour
  has_one :review, dependent: :destroy

  # Validations
  validates :date, presence: true
  validates :amount_of_people, presence: true, length: { minimum: 1 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reservation

  # Validations
  validates :reservation, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tours, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  # has_many :chatrooms, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  protected

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :avatar)}

   devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :name, :email, :password, :current_password, :avatar)}
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # def index
  #   @tour = Tour.find(params[:id])
  #   @favorites = Favorite.all
  # end

  def create
    @favorite = Favorite.new
    @favorite.user = current_user
    @tour = Tour.find(params[:tour_id])
    @favorite.tour = @tour
    authorize(@favorite)
    @favorite.save
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js {}
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    authorize(@favorite)
    @tour = @favorite.tour
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js {}
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @tours = Tour.all
    if params[:query].present?
      sql_query = " \
      tours.category @@ :query \
      tours.city @@ :query \
      tours.description @@ :query \
      "
      @tours = Tour.where(sql_query, query: "%#{params[:query]}%")
    else
      @tours = Tour.all
    end
  end

  def dashboard
    # @reservations = policy_scope(Reservation).where(user: current_user).order(created_at: :desc)
    @requests = Reservation.joins(:tour).where(tour: { user: current_user }).reverse_order
    # @user = current_user
    # @tour.user = @user
    @favorites = Favorite.all
    # @favorites = current_user.favorites
    @reservation = Reservation.new
    @reservations = Reservation.all.reverse_order
    @tours = Tour.all.reverse_order
    # @chatroom = Chatroom.find_or_create_by(tour: @tour, user: current_user)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = policy_scope(Reservation).where(user: current_user).order(created_at: :desc)
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
    authorize(@reservation)
  end

  def create
    @user = current_user
    @tour = Tour.find(params[:tour_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.user = @user
    @reservation.tour = @tour
    if @reservation.date != nil
      authorize(@reservation)
      if @reservation.save
        # redirect_to reservation_path(@reservation), notice: "Reservation was saved succsessfully!"
        # redirect_to tour_path(@tour), notice: "Reservation was saved succsessfully!"
      else
        redirect_to tour_path(@tour), notice: "Could not create Reservation!"
      end
    else
      authorize(@reservation)
      redirect_to tour_path(@tour), notice: "Enter a Date for the Reservation!"
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    authorize(@reservation)
    @reservation.destroy
    redirect_to dashboard_path, notice: "Reservation was cancelled succsesfully!"
  end

  def update
    @reservation = Reservation.find(params[:id])
    authorize(@reservation)

    if params[:approve] == "true"
      @reservation.approved = true
      @reservation.declined = false
    else
      @reservation.declined = true
      @reservation.approved = false
    end
    @reservation.save
  end

  private

  def reservation_params
    params.require(:reservation).permit(:user_id, :tour_id, :date, :amount_of_people, :total_price, :approved)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @tour = Tour.find(params[:tour_id])
    @reservation = Reservation.find(params[:reservation_id])
    authorize(@review)
  end

  def create
    @review = Review.new(review_params)
    @review.reservation = Reservation.find(params[:reservation_id])
    authorize(@review)
    if @review.save
      redirect_to tours_path
    else
      flash[:alert] = "Something went wrong. Please try again later!"
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:tour_rating, :review_description)
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_tour, only: %i[show edit update destroy]
  def index
    @tours = policy_scope(Tour).order(created_at: :desc)
    @tours = Tour.all
    if params[:query].present?
      sql_query = "category ILIKE :query OR city ILIKE :query"

      # @tours = Tour.where("category ILIKE ?", "%#{params[:query]}%")
      @tours = Tour.where(sql_query, query: "%#{params[:query]}%")
    else
      @tours = Tour.all
    end
    @favorite = Favorite.new
  end

  def show
    authorize(@tour)
    @tour = Tour.find(params[:id])
    @reservations = Reservation.all
    @reservations = Reservation.new
    @favorite = Favorite.new
  end

  def new
    @tour = Tour.new
    authorize(@tour)
  end

  def create
    if current_user.role == "Admin" || current_user.role == "Tour Guide"
      @tour = Tour.create(tour_params)
      @user = current_user
      @tour.user = @user
      authorize(@tour)
      if @tour.save
        redirect_to tour_path(@tour)
      else
        render :show
      end
    else
      render :index
    end

  end

  def edit
    authorize(@tour)
  end

  def update
    authorize(@tour)
    @tour.update(tour_params)
    if @tour.save
      redirect_to tours_path
    else
      render :edit
    end
  end

  def destroy
    @tour.destroy
    redirect_to tours_path
  end

  private

  def tour_params
    params.require(:tour).permit(:name, :city, :description, :duration, :price, :category, photos: [])
  end

  def set_tour
    @tour = Tour.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/pages/_component.city-cards.erb
<div class="container my-5">
  <h2 class="text-center my-5 home-tours-subtitle">Perfect Places to Visit</h2>
  <div class="cards">
    <% @tours.sample(3).each do |tour| %>
      <% case tour.city %>
      <% when "Rio de Janeiro" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1617961583/jh1pprthz32yaanw99z6wpdiqmwt.jpg) ">
      <% when "Amsterdam" || "Netherlands" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1617961539/aimti1gz265owscbrgehnev13y19.jpg) ">
      <% when "Zaanse Schans" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1618085814/bgpbrjv0x974ql2l7ydwgt9cebpr.jpg) ">
      <% when "Iguaçu" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1617961593/p4s1azzuzi6bniirx881ach355n3.jpg) ">
      <% when "Sao Paulo" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1617961576/9hkgvacvmu4wuny8f1j3fc1cyrr8.jpg) ">
      <% when "Utrecht" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1617961549/w3wn6e5csxcgrfcejwwgn2p2mdxk.jpg) ">
      <% when "Lise" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1617961441/kluk4oc2p187ygrw562a5xys5xi8.jpg) ">
      <% when "The Hague" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1617961507/ilvmre9crz6zrjwtl74df3vn5540.jpg) ">
      <% when "Rotterdam" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1617961459/wfmscr8zj5mrgv4i9otkwtklsov3.jpg) ">
      <% when "San Blas" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1618556915/nglgrol2pgn5c9lrxefydfddhn9c.jpg) ">
      <% when "Belize" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1618557194/qdnxg5ufogie6bu1hfekr9puyddx.jpg) ">
      <% when "French Polynesia" %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1618557486/yk0socz5clpnw4negiu01zzhhe81.jpg) ">
      <% else %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dynirwhqr/image/upload/v1618557963/jo-san-diego-IbDfOJEjq8Y-unsplash_txxbie.jpg) ">
      <% end %>
      <%= link_to "#{tour.city}", tours_path(:query => tour.city ), class: "city-links" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/_component.product-card.erb
<div class="row cards-wrapper mt-4">
  <% @tours.sample(3).each do |tour| %>
    <div class="col-sm-6 col-md-4 col-lg-3 card-trip">
      <% if tour.photos.attached? %>
        <%= cl_image_tag tour.photos[0].key %>
      <% end %>
      <div class="card-trip-infos">
        <div>
          <%= link_to tour_path(tour), class: "index-link pb-1" do %>
            <h2><%= tour.city %>: <%= tour.name %></h2>
          <% end %>
          <p class="mt-2 rating-index-style"> <i class="fas fa-star"></i> <%= tour.average_rating %> (<%= tour.reviews.count%> <%= tour.reviews.count > 1 ? "reviews" : "review" %>)</p>
          <p class="mt-2 tour-duration-index"><i class="far fa-clock"></i> <%= tour.duration %> <%= tour.duration == 1 ? "hour" : "hours" %></p>
        </div>
        <h2 class="card-trip-pricing">€<%= tour.price %> p/p</h2>
          <% if tour.user.avatar.attached? %>
            <%= cl_image_tag tour.user.avatar.key, class: 'card-trip-user avatar-bordered' %>
          <% else %>
            <%= image_tag "https://images.unsplash.com/photo-1485178575877-1a13bf489dfe?ixid=MXwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MXwyNDgzNjQ1fHxlbnwwfHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60", class: 'card-trip-user avatar-bordered' %>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/_cta-images-section.erb
<div class="two-image__wrapper">
    <div class="two-image__one">
        <img src="https://res.cloudinary.com/dynirwhqr/image/upload/v1628260481/netherlands_g4nj3h.jpg" alt="">
    </div>
    <div class="two-image__text-box">
        <h2>You Enjoying your Holiday with the Best Tours!</h2>
        <a href="#">Find your tour</a>
    </div>
    <div class="two-image__two">
        <img src="https://res.cloudinary.com/dynirwhqr/image/upload/v1618083624/0twst14oxzfso9sguc4mwbjfylyb.jpg" alt="">
    </div>
</div>

app/views/pages/_favorites.html.erb
<h2 class="my-5">You favorited tours:</h2>
<% if @favorites.blank? %>
  <p>You haven't favorited a tour yet!</p>
<% else %>
  <% @favorites.each do |fav| %>
    <%= link_to tour_path(fav.tour), class: "index-cards" do %>
      <div class="card entire-card decrease-card-height" id="index-cards">
        <div class="card-product-infos">
          <div class="d-flex">
            <%= cl_image_tag fav.tour.photos[0].key, class: "decrease-image-size" %>
            <div class="card-body">
              <div class="favorite-card-content">
                <div class="d-flex">
                  <h2 class="mb-3" id="index-photographer"><%= fav.tour.full_name %></h2>
                  <p> <i class="fas fa-star"></i> <%= @tour.average_rating %> (<%= @tour.reviews.count%> <%= @tour.reviews.count > 1 ? "reviews" : "review" %>)</p>

                  <div id="tour-favorites-<%= fav.tour.id %>" class="index-heart-favorite">
                    <%= render 'favorites/favoriteJS', tour: fav.tour %>
                  </div>
                </div>
                <div id="index-price">
                  $ <%= fav.tour.price %>
                  <span>
                    /day
                  </span>
                </div>
                <p id="index-user">
                  Listed by: <%= fav.tour.user.first_name %>
                </p>
                <!-- <div>
                  <%= link_to (chatroom_path(@chatroom)) do %>
                    <i class="far fa-comment-dots"></i>
                  <% end %>
                </div> -->
              </div>
              <div class=" booking-box-favorites">
                <h2>Book your Tour</h2>
                <%= simple_form_for ([@tour, @reservations]) do |f| %>
                <%= f.input :date, as: :date, html5: true %>
                <%= f.input :amount_of_people, placeholder: 'E.g. 1' %>
                <div class="details-show-price py-2 pr-1">
                  <p class="text-center" id="priceCalculator" data-price="<%= @tour.price %>"> Total: € <%= number_with_precision(@tour.price, precision: 0) %> <span>p/p</span></p>
                </div>
                <%= f.submit "Book this tour!", class:"btn btn-danger w-100 button-design" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/pages/_myprofile.html.erb
<div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
  <div class="own-tour" id="own-tour">
    <h2 class="my-5">Your Tours:</h2>
    <div class="row cards-wrapper">
      <% @tours.each do |tour| %>
        <% if tour.user_id == current_user.id %>
          <div class="col-sm-8 col-md-4 col-lg-3 card-trip">
            <% if tour.photos.attached? %>
            <%= cl_image_tag tour.photos[0].key, class: "dashboard-my-tours-image" %>
            <% end %>
            <div class="card-trip-infos">
              <div>
                <%= link_to tour_path(tour), class: "index-link pb-1" do %>
                  <h2><%= tour.city %>: <%= tour.name %></h2>
                <% end %>
                <p class="mt-2 rating-index-style"> <i class="fas fa-star"></i> <%= tour.average_rating %> (<%= tour.reviews.count%> <%= tour.reviews.count > 1 ? "reviews" : "review" %>)</p>
                <p class="mt-2 tour-duration-index"><i class="far fa-clock"></i> <%= tour.duration %> <%= tour.duration == 1 ? "hour" : "hours" %></p>
                <!-- <p class="mt-2"><%= tour.description&.truncate(50, separator: " ") %></p> -->

              </div>
              <h2 class="card-trip-pricing">€<%= tour.price %></h2>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_request-cards.html.erb
<div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
  <div class="requests " id="requests">
    <h2 class="my-5">Your tours were booked for the following dates:</h2>
    <% if @requests.blank? %>
      <p>No one has booked your tour yet.</p>
    <% else %>
      <% @requests.each do |request| %>
        <div class="notification">
          <% if request.user.avatar.attached? %>
            <%= cl_image_tag request.user.avatar.key, class: "avatar-large shadow mobile-request-avatar" %>
          <% else %>
            <%= image_tag "user.png", class: "avatar-large shadow mobile-request-avatar" %>
          <% end %>
        <div class="notification-content">
          <p><strong><%= request.user.first_name %></strong> booked <%= request.tour.city %> <%= request.tour.name %></p>
          <p><strong> Tour date: <%= request.date.strftime("%-d %B %Y") %> </strong></p>
          <p><strong> For <%= request.amount_of_people %> person.</strong></p>
        </div>

        <div class="notification-actions">
          <div id="approved-<%= request.id %>">
            <%if !request.approved && !request.declined %>
              <%= link_to (reservation_path(request, approve: true)), method: :patch, remote: true, class: "approve-button" do%>
                <i class="far fa-check-circle"></i>
              <% end %>
              <%= link_to (reservation_path(request, approve: false)), method: :patch, remote: true, class: "reject-button" do %>
                <i class="far fa-times-circle"></i>
              <% end %>
            <% elsif request.approved %>
              <p>Approved</p>
            <% elsif request.declined %>
              <p>Declined</p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/pages/_reservations-cards.html.erb
<% @reservations.each do |res| %>
<% if res.user_id == current_user.id %>
  <div class="card-product mb-3">
    <%= cl_image_tag res.tour.photos[0].key, class: "decrease-image-size" %>
    <div class="card-product-infos reservation-card-content-wrapper">
      <%= link_to tour_path(res.tour), class: "index-cards" do %>
        <h2 class="mb-3" id="index-tour"><%= res.tour.city %>: <%= res.tour.name %></h2>
        <% end %>
        <p id="index-description"> You booked <%= res.tour.name %> for <strong> <%= res.date.strftime("%B %-d, %Y") %></strong>. </p>
        <p id="index-description-approved-<%=res.id%> ">
        <% if res.approved %>
          <p class="green-approved booking-status"> <%= "Approved by #{res.tour.user.first_name}" %> (<%= link_to "Remove from dashboard?", reservation_path(res), method: :delete, class: "no-hover-decoration" %>)</p>
          <% if res.review == nil %>
            <p> <%= link_to "Rate this Tour", new_tour_reservation_review_path(res.tour, res)  %> </p>
          <% end %>
        <% elsif !res.approved && !res.declined %>
          <p class="yellow-waiting booking-status"> <%= "Awating confirmation!" %> <strong>(<%= link_to "Cancel Reservation?", reservation_path(res), method: :delete, class: "no-hover-decoration" %>)</strong> </p>
        <% else %>
          <p class="red-declined booking-status"> <%= "Your booking has been declined by #{res.tour.user.first_name}" %> (<%= link_to "Remove from dashboard?", reservation_path(res), method: :delete, class: "no-hover-decoration" %>)</p>
        <% end %>
        </p>
        <div> <strong> Tour Price: € <%= res.tour.price %> x <%= res.amount_of_people %> person</strong></div>
        <p id="index-total-price">Total € <%= res.tour.price %></p>
    </div>
  </div>
  <% end %>
<% end %>

app/views/pages/_reservations_cards.html.erb
<% @reservations.each do |res| %>
  <div class="card entire-card decrease-card-height" id="index-cards">
    <div class="card-product-infos">
      <div class="d-flex">
        <%= cl_image_tag res.tour.photo.key, class: "decrease-image-size" %>
        <div class="card-body ">
          <div>
            <%= link_to tour_path(res.tour), class: "index-cards" do %>
            <h2 class="mb-3" id="index-photographer"><%= res.tour.name %></h2>
            <% end %>
            <p id="index-description"> You requested <%= res.tour.name %>`s services for <strong> <%= res.date.strftime("%B %-d, %Y") %></strong>. </p>
            <p id="index-description-approved-<%=res.id%> ">
            <% if res.approved %>
              <p class="green-approved booking-status"> <%= "Approved by #{res.tour.user.first_name}" %> (<%= link_to "Remove from dashboard?", reservation_path(res), method: :delete, class: "no-hover-decoration" %>)</p>
              <% if res.review == nil %>
                <p> <%= link_to "Rate this Tour", new_tour_reservation_review_path(res.tour, res)  %> </p>
              <% end %>
            <% elsif !res.approved && !res.declined %>
              <p class="yellow-waiting booking-status"> <%= "Not yet approved" %> (<%= link_to "Cancel Reservation?", reservation_path(res), method: :delete, class: "no-hover-decoration" %>) </p>
            <% else %>
              <p class="red-declined booking-status"> <%= "Your request was declined by #{res.tour.user.first_name}" %> (<%= link_to "Remove from dashboard?", reservation_path(res), method: :delete, class: "no-hover-decoration" %>)</p>
            <% end %>
            </p>
            <div id="index-price"> $ <%= res.tour.price %> <span class=""> /day</span></div>
            <p id="index-user">Listed by: <%= res.tour.user.first_name %></p>
            </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/dashboard.html.erb
<div class="dashboard-container">
  <div class="d-flex align-items-center">
    <div class="mr-3 my-3">
      <% if current_user.avatar.attached? %>
        <%= cl_image_tag current_user.avatar.key, class: 'preview-avatar mb-2 shadow', id: "navbarDropdown", data: { toggle: "dropdown" }, width: '55px', height: '55px' %>
      <% else %>
        <%= image_tag "user.png", class: 'preview-avatar mb-2', id: "navbarDropdown", data: { toggle: "dropdown" }, width: '55px', height: '55px'%>
      <% end %>
    </div>
    <h1 class="my-3 dashboard-header">Welcome <%= current_user.first_name %>! </h1>
  </div>

  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">My Bookings</a>
    </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Requests</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">My Tours</a>
      </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="favorites-tab" data-toggle="tab" href="#favorites" role="tab" aria-controls="favorites" aria-selected="false">Favorites</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class="reservations" id="reservations">
        <h2 class="my-5">You have booked the following tours:</h2>
        <%  if @reservations.blank? %>
          <p>You haven't booked a tour yet.</p>
        <% else %>
          <%= render "reservations-cards" %>
        <% end %>
      </div>

    </div>

    <%= render "request-cards" %>

    <%= render "myprofile" %>

    <div class="tab-pane fade" id="favorites" role="tabpanel" aria-labelledby="favorites-tab">
      <%= render "favorites" %>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(' <%= image_path 'amsterdam-tours.jpg' %> ');">
  <div class="container">
    <h1>Let's Discover the <strong> World </strong> <br> Together?</h1>
    <div class="mt-3 d-flex justify-content-center">
      <%= form_tag tours_path, method: :get do %>
        <div class="form-row">
          <div class="input-width">
            <%= text_field_tag :query,
            params[:query],
            class: "form-control search-text",
              placeholder: "Which city are you going?"%>
            </div>
              <%= submit_tag "Search", class: "btn btn-danger search-button" %>
          </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

<h2 class="text-center my-5 home-tours-subtitle">Amazing Tours You <br/>Can't Miss!</h2>

<%= render "component.product-card" %>

<%= render "cta-images-section" %>

<%= render "component.city-cards" %>